"""Initial migration2233.

Revision ID: dc01bcb4d9ef
Revises: 
Create Date: 2025-01-15 22:52:15.939648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc01bcb4d9ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_encounter')
    op.drop_table('party_player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party_player',
    sa.Column('party_id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('party_id', 'player_id')
    )
    op.create_table('player_encounter',
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'encounter_id')
    )
    # ### end Alembic commands ###
